### ISSUE TITLE
Special:Categories is not working

### ISSUE THREAD

**Issue by vvsvvsvvs** [HaloACL/HaloACL#12] opened 2015-04-01 18:29 UTC
includes/specials/SpecialCategories.php
TitleValue has no userCanReadEx() function
Solution:

       function formatRow( $result ) {
                $title = new TitleValue( NS_CATEGORY, $result->cat_title );
                /*op-patch|TS|2014-09-30|HaloACL|SafeTitle|start*/
                // See http://dmwiki.ontoprise.com:8888/dmwiki/index.php/SafeTitle
                $tuta = Title::newFromTitleValue($title);
                if (!$tuta->userCanReadEx()) {
                        return "";
                }

**Comment by hermannschwaerzlerUIBK** [comment] 2015-04-08 09:03
I can confirm this problem. The suggested solution of vvsvvsvvs works. 
With a slightly altered variable name this translates to this patch for the patches (tested by me for MW 1.23.7):

```patch
diff --git a/patch_for_MW1.22.4.txt b/patch_for_MW1.22.4.txt
index 0ff5ece..3782c36 100644
--- a/patch_for_MW1.22.4.txt
+++ b/patch_for_MW1.22.4.txt
@@ -176,13 +176,14 @@
                                                        Linker::link( $t ) .
 --- includes/specials/SpecialCategories.php    2014-10-16 19:21:52.401436154 +0200
 +++ includes_new/specials/SpecialCategories.php        2014-10-16 19:21:26.837309403 +0200
-@@ -121,6 +121,12 @@
+@@ -121,6 +121,13 @@
  
        function formatRow( $result ) {
                $title = Title::makeTitle( NS_CATEGORY, $result->cat_title );
 +              /*op-patch|TS|2009-06-19|HaloACL|SafeTitle|start*/
 +              // See http://dmwiki.ontoprise.com:8888/dmwiki/index.php/SafeTitle
-+              if (!$title->userCanReadEx()) {
++              $title_nftv = Title::newFromTitleValue($title);
++              if (!$title_nftv->userCanReadEx()) {
 +                      return "";
 +              }
 +              /*op-patch|TS|2009-06-19|end*/
diff --git a/patch_for_MW1.23.4.txt b/patch_for_MW1.23.4.txt
index 9d61f56..ae4b73c 100644
--- a/patch_for_MW1.23.4.txt
+++ b/patch_for_MW1.23.4.txt
@@ -123,13 +123,14 @@
                                                        Linker::link( $t ) .
 --- includes/specials/SpecialCategories.php
 +++ includes/specials/SpecialCategories.php
-@@ -172,6 +172,12 @@
+@@ -172,6 +172,13 @@
  
        function formatRow( $result ) {
                $title = new TitleValue( NS_CATEGORY, $result->cat_title );
 +              /*op-patch|TS|2014-09-30|HaloACL|SafeTitle|start*/
 +              // See http://dmwiki.ontoprise.com:8888/dmwiki/index.php/SafeTitle
-+              if (!$title->userCanReadEx()) {
++              $title_nftv = Title::newFromTitleValue($title);
++              if (!$title_nftv->userCanReadEx()) {
 +                      return "";
 +              }
 +              /*op-patch|TS|2014-09-30|end*/
diff --git a/patch_for_MW1.23.7.txt b/patch_for_MW1.23.7.txt
index 6e8f7f4..e67dc47 100644
--- a/patch_for_MW1.23.7.txt
+++ b/patch_for_MW1.23.7.txt
@@ -132,13 +132,14 @@
                                                        Linker::link( $t ) .
 --- includes/specials/SpecialCategories.php    2014-12-07 10:40:02.974038677 +0100
 +++ includes/specials/SpecialCategories.php    2014-12-07 10:40:29.658170993 +0100
-@@ -172,6 +172,12 @@
+@@ -172,6 +172,13 @@
  
        function formatRow( $result ) {
                $title = new TitleValue( NS_CATEGORY, $result->cat_title );
 +              /*op-patch|TS|2014-09-30|HaloACL|SafeTitle|start*/
 +              // See http://dmwiki.ontoprise.com:8888/dmwiki/index.php/SafeTitle
-+              if (!$title->userCanReadEx()) {
++              $title_nftv = Title::newFromTitleValue($title);
++              if (!$title_nftv->userCanReadEx()) {
 +                      return "";
 +              }
 +              /*op-patch|TS|2014-09-30|end*/
diff --git a/patch_for_MW1.24.1.txt b/patch_for_MW1.24.1.txt
index 6bb7a3f..bcc96e9 100644
--- a/patch_for_MW1.24.1.txt
+++ b/patch_for_MW1.24.1.txt
@@ -134,13 +134,14 @@
                                                        ( $s->page_is_redirect ? ' class="allpagesredirect"' : '' ) .
 --- includes/specials/SpecialCategories.php    2014-12-17 21:11:53.000000000 +0100
 +++ includes/specials/SpecialCategories.php    2015-03-22 15:16:45.073068001 +0100
-@@ -172,6 +172,12 @@
+@@ -172,6 +172,13 @@
  
        function formatRow( $result ) {
                $title = new TitleValue( NS_CATEGORY, $result->cat_title );
 +              /*op-patch|TS|2014-09-30|HaloACL|SafeTitle|start*/
 +              // See http://dmwiki.ontoprise.com:8888/dmwiki/index.php/SafeTitle
-+              if (!$title->userCanReadEx()) {
++              $title_nftv = Title::newFromTitleValue($title);
++              if (!$title_nftv->userCanReadEx()) {
 +                      return "";
 +              }
 +              /*op-patch|TS|2014-09-30|end*/
´´´

**Comment by hermannschwaerzlerUIBK** [comment] 2015-06-30 09:17
This issue is close-able due to the merging of merge request #15.

**Comment by wojteque** [comment] 2015-06-30 16:21
in this case im closing this issue.

**Closed** 2015-06-30 16:21 UTC
